// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDs09HGGjXgRCz8KzpmFsHx7_kskihFW4',
    appId: '1:990201936336:web:3709cde61abf1a047ce1d5',
    messagingSenderId: '990201936336',
    projectId: 'mis-labs-f2f4d',
    authDomain: 'mis-labs-f2f4d.firebaseapp.com',
    storageBucket: 'mis-labs-f2f4d.firebasestorage.app',
    measurementId: 'G-DMEWK9VNQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9BU2dUFX1jP0iiCdA-LJ0NEi29HtlR4U',
    appId: '1:990201936336:android:32fe5d2519385aef7ce1d5',
    messagingSenderId: '990201936336',
    projectId: 'mis-labs-f2f4d',
    storageBucket: 'mis-labs-f2f4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpoBDdC53sYVysy8NJTHmSjhxKPX_riIA',
    appId: '1:990201936336:ios:e21cf604467203f07ce1d5',
    messagingSenderId: '990201936336',
    projectId: 'mis-labs-f2f4d',
    storageBucket: 'mis-labs-f2f4d.firebasestorage.app',
    iosBundleId: 'com.example.lab1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpoBDdC53sYVysy8NJTHmSjhxKPX_riIA',
    appId: '1:990201936336:ios:e21cf604467203f07ce1d5',
    messagingSenderId: '990201936336',
    projectId: 'mis-labs-f2f4d',
    storageBucket: 'mis-labs-f2f4d.firebasestorage.app',
    iosBundleId: 'com.example.lab1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDs09HGGjXgRCz8KzpmFsHx7_kskihFW4',
    appId: '1:990201936336:web:a0a9c8a96dd1bbbc7ce1d5',
    messagingSenderId: '990201936336',
    projectId: 'mis-labs-f2f4d',
    authDomain: 'mis-labs-f2f4d.firebaseapp.com',
    storageBucket: 'mis-labs-f2f4d.firebasestorage.app',
    measurementId: 'G-D3EE2V1617',
  );
}
